name: Package VSIX Extension

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Obtener el código fuente del repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Instalar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Paso 4: Instalar VSCE (herramienta para empaquetar)
      - name: Install vsce
        run: npm install -g vsce

      # Paso 5: Empaquetar la extensión en un archivo VSIX
      - name: Package the extension as a .vsix file
        run: vsce package

      # Paso 6: Subir el archivo .vsix como artefacto del flujo de trabajo
      - name: Upload VSIX as artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-extension.vsix
          path: '*.vsix'
